### ISSUE TITLE
Loosen Restrictions for Data Providers

### ISSUE THREAD

**Issue by tobiasschweizer** [Connectome-Consortium/rescs_shacl_shapes#36]
The experience over the past months has shown, that some data is not provided although from a logical point the expectation is sound.

Restrictions have to be loosened for:
- https://github.com/Connectome-Consortium/rescs_shacl_shapes/pull/4
- https://github.com/Connectome-Consortium/rescs_shacl_shapes/pull/25

`sh:minCount` 1 had to be removed for:
- `CreativeWork`
    - ~~`author`~~ 
    - `conditionsOfAccess`
    - `inLanguage`

- `Person`
    - `affiliation`
    - `jobTitle`

- `MediaObject` (`Datadownload`)
   - `contentSIze`
   - `contentUrl`

@v0idness Regarding `CreativeWork:author`: Are there `ScholarlyArticle` without any author?

**Comment by v0idness** [comment]
As far as I am aware and as of the current state of the data, there are no articles without author.

**Comment by tobiasschweizer** [comment]
> As far as I am aware and as of the current state of the data, there are no articles without author.

Do we still need the removal of `sh:minCount` 1 for `CreativeWork:author` then (https://github.com/Connectome-Consortium/rescs_shacl_shapes/pull/25)?

**Comment by v0idness** [comment]
Added the minCount back in https://github.com/Connectome-Consortium/rescs_shacl_shapes/pull/25/commits/a3e603557bbb137f084e35f84374e8b42f208576

**Comment by tobiasschweizer** [comment]
Ok, thanks, I'll come up with a PR containing the changes described in https://github.com/Connectome-Consortium/rescs_shacl_shapes/issues/36#issue-1269308137. In #4, there are some changes that are even only relevant for local validation with `pyshacl` (blank nodes) and I have no intention to merge them ever.
