### ISSUE TITLE
List Dependencies and their Licenses

### ISSUE THREAD

**Issue by tobiasschweizer** [Connectome-Consortium/rescs_shacl_shapes#5]
This repo has the following dependencies listed in the sections below.

## Data Model:
- schema.org: https://github.com/schemaorg/schemaorg, schemas and docs on schema.org:  Creative Commons Attribution-ShareAlike License (version 3.0), http://creativecommons.org/licenses/by-sa/3.0/; source code for docs site: Apache 2, https://github.com/schemaorg/schemaorg/blob/main/LICENSE; see https://schema.org/docs/faq.html#18
- SHACL: https://www.w3.org/TR/shacl/ -> W3C spec
- DASH Data Shapes https://datashapes.org/schema -> no license info given

## Software:
- Forge, https://github.com/BlueBrain/nexus-forge, GNU LESSER GENERAL PUBLIC LICENSE, https://github.com/BlueBrain/nexus-forge/blob/master/LICENSE.txt
- nexussdk, https://github.com/BlueBrain/nexus-python-sdk, Apache-2.0 License, https://github.com/BlueBrain/nexus-python-sdk/blob/master/LICENSE.txt
- PyLD: https://github.com/digitalbazaar/pyld, New BSD License, https://github.com/digitalbazaar/pyld/blob/master/LICENSE
- requests, https://github.com/psf/requests, Apache-2.0 License, https://github.com/psf/requests/blob/main/LICENSE
- types-requests, https://github.com/python/typeshed,  [Apache-2.0 License](https://github.com/python/typeshed/blob/master/LICENSE)
- pyparsing, https://github.com/pyparsing/pyparsing, MIT License, https://github.com/pyparsing/pyparsing/blob/master/LICENSE
- pyshacl, https://github.com/RDFLib/pySHACL, Apache-2.0 License, https://github.com/RDFLib/pySHACL/blob/master/LICENSE.txt
- python-decouple, https://github.com/henriquebastos/python-decouple, MIT License, https://github.com/henriquebastos/python-decouple/blob/master/LICENSE
- rdflib, https://github.com/RDFLib/rdflib, BSD-3-Clause License, https://github.com/RDFLib/rdflib/blob/master/LICENSE
- mypy, https://github.com/python/mypy, [MIT](https://github.com/python/mypy/blob/master/LICENSE)
See https://github.com/Connectome-Consortium/rescs_shacl_shapes/blob/main/requirements.txt for this lib's Python deps.

Python itself and its standard libs (os, json etc.) are open-source, see https://github.com/python/cpython/tree/3.10 and https://github.com/python/cpython/blob/main/LICENSE. Note that not all releases are GPL compatible, see https://github.com/python/cpython/blob/a4cb31927a1f0ee31025ea1ca82fcbfad44755dc/LICENSE#L22-L25.

## Documentation
- Ontospy, https://github.com/lambdamusic/Ontospy,  MIT License, https://github.com/lambdamusic/Ontospy/blob/master/LICENSE
- Django, https://github.com/django/django, https://github.com/django/django/blob/main/LICENSE, redistribution allowed under the same conditions as stated by the license
- Pygments, https://github.com/pygments/pygments, [BSD-2-Clause License](https://github.com/pygments/pygments/blob/master/LICENSE) 
- pandoc, https://github.com/jgm/pandoc, the [GPL],
version 2 or later, https://github.com/jgm/pandoc/blob/master/COPYRIGHT

**Comment by 9812342** [comment]
Rescs.org shall be open-sourced, irrespective of the other developments within the Connectome RI project. Next step @tobiasschweizer as discussed with SWITCH legal: 
1. Discuss with TSH the substantial contributions to code and other substantial contributions.  
2. Definition of minimum common denominator of the licences used? (e.g. by using different comparison sheets of the licenses).
3. Choice of license with "minimum common denominator" (if possible).

**Comment by tobiasschweizer** [comment]
I did some research using the following sources:
- https://opensource.org/faq (the Open Source Initiative offers rules defining Open Source Software)
- https://snyk.io/learn/open-source-licenses/ (SNYK is a cybersecurity company offering services for open source projects such as license compliance)

**Comment by 9812342** [comment]
Thank you Tobias. Is it correct to assume that going for a copyleft license is the minimum common denominator considering all the tools and licences present at the moment?

**Comment by tobiasschweizer** [comment]
> Thank you Tobias. Is it correct to assume that going for a copyleft license is the minimum common denominator considering all the tools and licences present at the moment?

I guess we should go for the least restrictive copyleft license applicable given our dependencies. Or we could decide not to use any dependency with a copyleft license but this might have a lot of unforeseeable implications.

However, I am not a legal expert so we should present this summary to someone first to see if it is correct.

**Comment by 9812342** [comment]
Splendid. Shall I ask Angelo for a 30min call on this? Could you present the review to him?

**Comment by tobiasschweizer** [comment]
> Splendid. Shall I ask Angelo for a 30min call on this? Could you present the review to him?

yes, sure, will do

**Comment by tobiasschweizer** [comment]
From the email correspondence (10.02.2022):

> Aus unserer Sicht brauchen wir eine Lizenzunterscheidung zwischen:
- Entwicklung Datenmodell (Quellfiles auf Github + „Build-Process” inkl. der nötigen Software und deren Lizenzen dafür) => Logik der Datenstruktur & Tooling.
- Dokumentation des Datenmodell (auf Rescs.org) => die Beschreibung der Logik in „menschenlesbarer Form“.

**Comment by tobiasschweizer** [comment]
Together with Angelo we defined the steps needed to finalise this task:
- folders `ontology` and `shapes` will be licensed using CC SharedAlike (like schema.org model)
- folder `scripts` will be licensed using a GPL
- The copyright notice will have to exclude the folders `ontology` and `shapes` from the GPL license, like here: [pandoc/COPYRIGHT at master · jgm/pandoc](https://github.com/jgm/pandoc/blob/master/COPYRIGHT)
